name: Cypress Tests
on:
  push:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
      - name: Executar testes Cypress
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: 'http://localhost:3000'
          MINHA_CHAVE_SECRETA: ${{ secrets.MINHA_CHAVE_SECRETA }}


# name: End-to-end tests
# on: push
# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         env:
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#         with:
#           command: npm run test:cloud
